#!/bin/csh -f

run show_all show_all

setenv IFV_HIER des.algo_top.a1_loop.algo

run fifo_oflw_check fifo_oflw_check
run fifo_oflw_ifc_check fifo_oflw_ifc_check
run t1_ctrl_loop_check t1_ctrl_loop_check 
run t2_ctrl_loop_check t2_ctrl_loop_check 
run t1_vld_del_check t1_vld_del_check 
run t2_vld_del_check t2_vld_del_check 
run dup_id_check dup_id_check
run t1_range_check t1_range_check
run t2_range_check t2_range_check

run rd_vld_check rd_vld_check
run rd_dout_check rd_dout_check

setenv IFV_HIER    des.algo_top.a2_loop*.algo
setenv IFV_HIER_A1 des.algo_top.a1_loop.algo

run a2_mem_check a2_mem_check
run a2_mem_range_check a2_mem_range_check
run a2_eccmem_chk_check a2_eccmem_chk_check
run a2_np2_check a2_np2_check
run a2_forward_check a2_forward_check
run a2_rmem_check a2_rmem_check
run a2_vdout_int_check a2_vdout_int_check
run a2_fakemem_check a2_fakemem_check
run a2_dout_check a2_dout_check

# t4 stack and align check
setenv IFV_HIER    des.algo_top.t\*_loop\[\*\].align_loop.infra
setenv IFV_HIER_A1 des.algo_top.a1_loop.algo

run align_check t4_align_check
run mem_chk_check t4_mem_chk_check
run align_dout_check t4_align_dout_check

setenv IFV_HIER   des.algo_top.t\*_loop\[\*\].stack_loop.infra
setenv IFV_HIER_A1 des.algo_top.a1_loop.algo

run stack_check t4_stack_check
run stack_dout_check t4_stack_dout_check

setenv IFV_HIER des.algo_top.t\*_loop\[\*\].align_loop.infra
setenv IFV_HIER_2 des.algo_top.t\*_loop\[\*\].stack_loop.infra
setenv IFV_HIER_A1 des.algo_top.a1_loop.algo

run t1_mem_check t4_mem_check
run t1_port_check t4_port_check

# t1-t3 stack and align check
setenv IFV_HIER    des.algo_top.t\*_loop\[\*\].t\*_loop\[\*\].align_loop.infra
setenv IFV_HIER_A1 des.algo_top.a1_loop.algo

run align_check t1t2t3_align_check
run mem_chk_check t1t2t3_mem_chk_check
run align_dout_check t1t2t3_align_dout_check

setenv IFV_HIER   des.algo_top.t\*_loop\[\*\].stack_loop.infra
setenv IFV_HIER_A1 des.algo_top.a1_loop.algo

run stack_check t1t2t3_stack_check
run stack_dout_check t1t2t3_stack_dout_check

setenv IFV_HIER des.algo_top.t\*_loop\[\*\].align_loop.infra
setenv IFV_HIER_2 des.algo_top.t\*_loop\[\*\].stack_loop.infra

run t1_mem_check t1t2t3_mem_check
run t1_port_check t1t2t3_port_check

