#!/bin/csh -f

run show_all show_all

setenv IFV_HIER des.algo_top.a1_loop.algo

run mem_range_check mem_range_check
run fakemem_check fakemem_check
run dout_check dout_check

setenv IFV_HIER des.algo_top.t\*_loop\[\*\].\*.align_loop.infra
setenv IFV_HIER_2 des.algo_top.t\*_loop\[\*\].\*.align_loop.infra

run align_check align_check
run align_dout_check align_dout_check

setenv IFV_HIER des.algo_top.t\*_loop\[\*\].\*.stack_loop.infra

run stack_check stack_check
run stack_dout_check stack_dout_check

setenv IFV_HIER des.algo_top.t\*_loop\[\*\].\*.align_loop.infra
setenv IFV_HIER_2 des.algo_top.t\*_loop\[\*\].\*.stack_loop.infra

run t1_mem_check t1_mem_check
run t1_port_check t1_port_check

setenv IFV_HIER des.algo_top.a1_loop.algo
setenv IFV_HIER_2 des.algo_top.t\*_loop\[\*\].\*.align_loop.infra
setenv IFV_HIER_3 des.algo_top.t\*_loop\[\*\].\*.stack_loop.infra

run pdout_check pdout_check
run port_check port_check
