#!/bin/csh -f

if($#argv == 0) then
    echo "Usage: $0 <top_module_name> [-noob] [-refr]"
    echo "   this runs only from <cut-dir>/run_sample/<cut-name> dir"
    echo "   -noob : use this if cut was generated with -noob"
    echo "   -refr : use this if cut was generated for eDRAM"
    exit (1);
endif
echo "cmdline: $0 $argv"
set TOP=$argv[1]
set NOOB=0
setenv IFV_REFR 0
if ($#argv == 2) then
    if ($argv[2] == '-noob') then
        set NOOB=1
    else if ($argv[2] == '-refr') then
        setenv IFV_REFR 1
    endif
else if ($#argv == 3) then
    if (($argv[2] == '-noob') || ($argv[3] == '-noob')) then
      set NOOB=1
    endif
    if (($argv[2] == '-refr') || ($argv[2] == '-refr')) then
      setenv IFV_REFR 1
    endif
endif
set SCRIPT=`readlink -f "$0"`
set SCRIPTPATH=`dirname "$SCRIPT"`
set BINPATH=`dirname "$0"| sed 's:verilogparser/.*$:verilogparser:'`
set BINDIR=`readlink -f "$BINPATH"`
set IPDIR="$BINDIR/ip_obfuscated"

set TOPV="../../../rtl/${TOP}.v"
set DESLIB=`\ls ${IPDIR}/common/rtl/memoir_design_library*.v`
if ($NOOB == 1) then
   set DESLIB=`\ls ${IPDIR}/memoir_design_library*.v`
endif
echo "design library used: $DESLIB"

set TCLA="+tcl+${SCRIPTPATH}"
set CMDP="iev +64bit -F filelist +define+FORMAL +licq +exit +top+${TOP}"

\rm -fr INCA_libs filelist

echo $SCRIPTPATH
echo $TOPV >! filelist
echo "$DESLIB" >> filelist

alias run '\rm -f \!:2.log; echo $CMDP ${TCLA}/\!:1.tcl -l \!:2.log; $CMDP ${TCLA}/\!:1.tcl -l \!:2.log;'
run show_all show_all

setenv IFV_HIER des.algo_top.a1_loop.algo

run mrnrwpw_rl_mem_check mrnrwpw_rl_mem_check
run mrnrwpw_rl_mem_range_check mrnrwpw_rl_mem_range_check
run mrnrwpw_rl_np2_check mrnrwpw_rl_np2_check
#run mrnrwpw_rl_ecc_check mrnrwpw_rl_ecc_check
#run mrnrwpw_rl_smem_check mrnrwpw_rl_smem_check
run mrnrwpw_rl_forward_check mrnrwpw_rl_forward_check
run mrnrwpw_rl_sold_fwd_check mrnrwpw_rl_sold_fwd_check
run mrnrwpw_rl_rmem_check mrnrwpw_rl_rmem_check
run mrnrwpw_rl_vdout_int_check mrnrwpw_rl_vdout_int_check
run mrnrwpw_rl_vmem_check mrnrwpw_rl_vmem_check
run mrnrwpw_rl_srch_check mrnrwpw_rl_srch_check
run mrnrwpw_rl_fakemem_check mrnrwpw_rl_fakemem_check
run mrnrwpw_rl_dout_check mrnrwpw_rl_dout_check
run mrnrwpw_rl_sdiff_check mrnrwpw_rl_sdiff_check

setenv IFV_HIER des.algo_top.a2_loop\[\*\].algo

run nror1w_dup_mem_check nror1w_dup_mem_check
run nror1w_dup_mem_range_check nror1w_dup_mem_range_check
run nror1w_dup_fakemem_check nror1w_dup_fakemem_check
run nror1w_dup_dout_check nror1w_dup_dout_check

if ($IFV_REFR > 1) then
#  setenv IFV_HIER des.algo_top.t\*_loop\[\*\].\*.refr_loop.infra
#  run prefr_check prefr_check
#  run refr_bitcell refr_bitcell
endif

setenv IFV_HIER des.algo_top.t\*_loop\[\*\].\*.align_loop.infra

run align_check align_check
run align_mem_check align_mem_check
run align_dout_check align_dout_check

setenv IFV_HIER des.algo_top.t\*_loop\[\*\].align_loop.infra

run align_mrnw_check align_mrnw_check
run align_mrnw_mem_check align_mrnw_mem_check
run align_mrnw_dout_check align_mrnw_dout_check

setenv IFV_HIER des.algo_top.t\*_loop\[\*\].stack_loop.infra

run stack_check stack_check
run stack_dout_check stack_dout_check

setenv IFV_HIER des.algo_top.t\*_loop\[\*\].align_loop.infra
setenv IFV_HIER_2 des.algo_top.t\*_loop\[\*\].stack_loop.infra

run t_mem_check t_mem_check
run t_port_check t_port_check

setenv IFV_HIER des.algo_top.a2_loop\[\*\].algo
setenv IFV_HIER_2 des.algo_top.t\*_loop\[\*\].\*.align_loop.infra
if ($IFV_REFR > 0) then
setenv IFV_HIER_3 des.algo_top.t\*_loop\[\*\].\*.refr_loop.infra
endif

run a2_pdout_check a2_pdout_check
run a2_pdout_err_check a2_pdout_err_check
run a2_port_check a2_port_check

setenv IFV_HIER des.algo_top.a1_loop.algo
setenv IFV_HIER_2 des.algo_top.a2_loop\[\*\].algo
setenv IFV_HIER_3 des.algo_top.t\*_loop\[\*\].align_loop.infra

run a1_pdout_check a1_pdout_check
run a1_pdout_err_check a1_pdout_err_check
run a1_port_check a1_port_check
